### ISSUE TITLE
Bug : drag n drop doesnt work in structure

### ISSUE THREAD

**Issue by CPASimUSante** [iCAPLyon1/WebsiteBundle#3]
I've created a website with several pages and sub pages. But if i try to move the one subpage to another level, when i drag-drop it, it stays at the same place (v6.0.2)
![bug-dnd](https://cloud.githubusercontent.com/assets/14015697/11183236/ebb05f66-8c70-11e5-8f05-c6c773d9a183.png)

Is it normal ? If yes, how to change the level ?
Maybe a selectbox, like in wiki, blog could be useful

Thank you

**Comment by ptsavdar** [comment]
The issue is now fixed. Thank you for your indication.
